### PR TITLE
Fix typo in render_file() use of @_

### PR DESCRIPTION
**Pull request by kaoru**
The logic for correctly handling hashref contexts which is used in render() was not correctly being used in render_file().

None of the tests fail before or after this change. Lame. If I were a better person I would have written a failing test for you... :-)

### CODE REVIEW

**Comment by vti** [comment]
Maybe there is a change for you to become a better person and write the test? ;)

**Comment by kaoru** [comment]
There certainly is... maybe this evening, more likely tomorrow evening.

**Comment by kaoru** [comment]
Ah I started writing a test and found that it's impossible to trigger that bug, because the context check is duplicated again in _parse itself.

New pull request incoming...

**Comment by kaoru** [comment]
There are now three commits on this pull request!

**Pull request merged**
