### PR TITLE
Implement the same behavior as in JS Mustache version for indexing arrays

### PR DESCRIPTION
**Pull request by FCO**
Make it possible to do (as in JS):
```perl
$template->render("Position 0 of array: {{array.0}}", {array => ["data"]})
```

### CODE REVIEW

**Comment by vti** [comment]
Would be nice if you could write a test for that. Thanks!

**Comment by FCO** [comment]
is that ok? (and thank you!)

**Comment by vti** [comment]
Thanks!

**Comment by FCO** [comment]
Thank you!
Im sorry about that, but do you have any plan of sending that to cpan?
Thanks and congratulations for your clean code!




Just another Perl Hacker,
Fernando (SmokeMachine)

2016-04-18 19:06 GMT-03:00 Viacheslav Tykhanovskyi <notifications@github.com

**Comment by vti** [comment]
I just uploaded it. Enjoy! :)

**Pull request merged**
